[package]
description = "Parser for BER/DER encoded data"
license = "MIT/Apache-2.0"
keywords = ["BER","DER","ASN1","parser","nom"]
homepage = "https://github.com/rusticata/der-parser"
repository = "https://github.com/rusticata/der-parser.git"
name = "der-parser"
version = "3.0.2"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["parser-implementations"]
readme = "README.md"
edition = "2018"

include = [
  "LICENSE-*",
  "README.md",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "bench/*.rs",
  "src/*.rs",
  "src/ber/*.rs",
  "src/der/*.rs",
  "tests/*.rs"
]

[package.metadata.docs.rs]
features = [ "bigint" ]
all-features = true

[dependencies]
nom = "5.0"
rusticata-macros = "2.0.2"
num-bigint = { version = "0.2", optional = true }
num-traits = { version = "0.2", optional = true }

[features]
default = []
bigint = ["num-bigint", "num-traits"]

[dev-dependencies]
hex-literal = "0.2"
pretty_assertions = "0.6"

[badges]
travis-ci = { repository = "rusticata/der-parser" }
